eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.72.212:1433;databaseName=PRODUCTION;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  servlet:
    # Giới hạn kích thước file tải lên
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      # Giới hạn tổng số lượng file tải lên
      file-size-threshold: 2MB

  aop:
    auto: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true

swagger:
  enabled: true

logging:
  level:
    org.springframework: ERROR
